# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: my-blog-b38tyl8oop
google_analytics: dbyll
title: Chris Wong Chun Kau
timezone: Asia/Hong Kong

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Chris Wong’s Blog
      comments: true

description: Chris Wong’s Blog
author:
  name: Chris Wong
  facebook: wonchunkau
  email: chrisckwong821@gmail.com
  github: chrisckwong821
  twitter: chrisckwong821
  linkedin: chris-chun-kau-wong-8a05bba4/
  medium: https://medium.com/@chris_whirlwind
  bio: Python Developer
  email_md5: 4c49576fe83075f5d36fec69fa7bc296


rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1
#sidebar_image: https://github.com/chrisckwong821/Blog/blob/gh-pages/assets/media/Profile.png

BASE_PATH: 
baseurl: ''

gems:
  - jekyll-paginate

